In [18]:
import numpy as np
arr = np.array(1)
arr1 = np.array([[ 1, 2, 3],
                [2, 3, 4]])
arr2 = np.array([[[1, 2, 3], [3, 4, 5]], [[1, 2, 3],[3, 4, 5]]])
print(arr)
print(np.__version__)
print(type(arr))
print(arr)
print("--------------------------------------------")
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)



1
2.4.2
<class 'numpy.ndarray'>
1
--------------------------------------------
0
2
3


In [26]:
import numpy as np

arr = np.array([[[1, 2, 3], [6, 7, 8], [4, 5, 6]]])
print(arr[0])
print("second element of the first list:", arr[0,1])
print("Access the third element of the second array of the first array:", arr[0, 1, 2])


[[1 2 3]
 [6 7 8]
 [4 5 6]]
second element of the first list: [6 7 8]
Access the third element of the second array of the first array: 8


In [30]:
import numpy as np

arr = np.array([[1, 2, 3], [6, 7, 8]])
print("last element from the second arra:", arr[1, -1])

last element from the second arra: 8


In [40]:
#[start:end:step]

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[0:4])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[0:5:2])
print(arr[0:5:1])

[1 2 3 4]
[5]
[1 2 3 4]
[3 4]
[1 3 5]
[1 2 3 4 5]


In [45]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1:4])

[2 3]


In [55]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])
print(arr.dtype)

arr1 = np.array([1, 2, 3, 4, 5], dtype="S")
print(arr1.dtype)


[3 8]
int64
|S1


In [57]:
import numpy as np
arr = np.array([2, 4, 5])
new = arr.copy()
arr[0] = 42
print(arr)

[42  4  5]


In [80]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new = arr.view()
arr[0] = 42
print(arr)
print(arr.shape)
new1 = arr.reshape(4, 3)
print(new1)
print(arr.reshape(-1))

[42  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[42  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[42  2  3  4  5  6  7  8  9 10 11 12]


In [87]:
import numpy as np
arr = np.array([[[1, 2, 3,], [2, 3, 4], [ 4, 5, 6]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
2
3
4
4
5
6


In [92]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 3, 4])
n = np.concatenate((arr1, arr2))
newwer = np.array_split(arr1, 2)
print(n)
print("-"*100)
print(newwer)

[1 2 3 2 3 4]
----------------------------------------------------------------------------------------------------
[array([1, 2]), array([3])]
